export const SELECT_PRODUCT_TYPE = "SELECT_PRODUCT_TYPE";

export const IS_PRODUCT_CATEGORIES_OPEN = "IS_PRODUCT_CATEGORIES_OPEN";

export const IS_SALE_CATEGORIES_OPEN = "IS_SALE_CATEGORIES_OPEN";

export const FIND_ALL_BY_TYPE = "FIND_ALL_BY_TYPE";

export const TRACK_PAGINATION = "TRACK_PAGINATION";

export const USER_SESSION = "USER_SESSION";

export const DELETE_USER_SESSION = "DELETE_USER_SESSION";

export const SAVE_FORGOT_PASSWORD_USERNAME = 'SAVE_FORGOT_PASSWORD_USERNAME';

export const CLEAR_FORGOT_PASSWORD_USERNAME = 'CLEAR_FORGOT_PASSWORD_USERNAME';